## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
matrix:
  include:
    - os: linux
      julia: 0.7
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.0
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.7
      env: TESTCMD="julia"
    - os: osx
      julia: 1.0
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"

script:
    - $TESTCMD -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("JuliaKara"); Pkg.test("JuliaKara"; coverage=true)'
    
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("JuliaKara")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("JuliaKara")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - $TESTCMD -e 'using Pkg; cd(Pkg.dir("JuliaKara")); include(joinpath("docs", "make.jl"))'
